version: "3"
services:
  web:
    image: awesanam/socialmedia:1.3
    network_mode: bridge
    ports:
      - 8000:8000
    # volumes:
    #   - .:/app
    env_file:
      - ./.env
    depends_on:
      - redis
    environment:
      REDIS_PORT: 6379
    restart: always
    links:
      - redis
  redis:
    image: redis:latest
    restart: always
    network_mode: bridge
    ports:
      - 6379:6379

volumes:
  redis:
    driver: local
